# Generated by Django 3.2.8 on 2021-11-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_oredrs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oredrs',
            new_name='Orders',
        ),
    ]
